name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      # Add additional steps for running server tests

      - name: Start server
        run: npm start
        working-directory: ./server

      # Add additional steps for running client tests
      - name: Run client tests
        run: npm test
        working-directory: ./client
